// Copyright (C) 2026 Industrial Algebra
// SPDX-License-Identifier: Apache-2.0

//! Generator for `schubert-tsukoshi/src/lr-tables.ts`.
//!
//! Computes Littlewood-Richardson coefficient tables for Gr(2,4), Gr(3,6),
//! and Gr(4,8) using amari-enumerative's *exact* `lr_coefficient`, then emits
//! a TypeScript module. This guarantees the TypeScript lookup tables are
//! byte-faithful to the Rust math — no transcription risk.
//!
//! Run:
//! ```text
//! cargo run --example generate_ts_lr_tables > schubert-tsukoshi/src/lr-tables.ts
//! ```
//!
//! # Mathematical basis
//!
//! Schur functions are homogeneous: `s_λ · s_μ = Σ c^ν_{λμ} s_ν` where only
//! partitions `ν` of size `|λ| + |μ|` appear. So the pairwise product table is
//! naturally graded and compact. The TS `check()` multiplies the position and
//! required classes via this table, then reads the coefficient of the point
//! class `σ_{(n-k)^k}`:
//!
//! - coefficient `> 0` → **Granted** (that many configurations)
//! - coefficient `== 0`, codim sum `== dim` → **Impossible** (e.g. σ₂·σ₁₁)
//! - codim sum `< dim` → **Underconstrained**
//!
//! This is exactly the LR branch of `Schubert::AccessController::check`.

use amari_enumerative::{schubert_product, Partition};
use std::fmt::Write;

/// One Grassmannian to tabulate.
struct Grass {
    k: usize,
    n: usize,
}

impl Grass {
    const fn cols(&self) -> usize {
        self.n - self.k
    }
    const fn dim(&self) -> usize {
        self.k * (self.n - self.k)
    }

    /// Enumerate every partition fitting in the k × (n-k) box, including the
    /// empty partition. Each is a non-increasing Vec<usize> with ≤ k parts,
    /// each ≤ cols.
    fn partitions_in_box(&self) -> Vec<Vec<usize>> {
        let mut out = Vec::new();
        out.push(Vec::new()); // empty partition (unit class)
        let mut current: Vec<usize> = Vec::new();
        self.recurse(self.cols(), &mut current, &mut out);
        // Sort by (size, then lexicographic) for stable output.
        out.sort_by(|a, b| {
            let sa: usize = a.iter().sum();
            let sb: usize = b.iter().sum();
            sa.cmp(&sb).then_with(|| a.cmp(b))
        });
        out
    }

    fn recurse(&self, max_part: usize, current: &mut Vec<usize>, out: &mut Vec<Vec<usize>>) {
        if current.len() == self.k {
            return;
        }
        // next part is between 1 and max_part, non-increasing
        for part in (1..=max_part).rev() {
            current.push(part);
            out.push(current.clone());
            self.recurse(part, current, out);
            current.pop();
        }
    }
}

/// Stable string key for a partition: comma-joined parts, "" for empty.
fn key(part: &[usize]) -> String {
    part.iter()
        .map(|p| p.to_string())
        .collect::<Vec<_>>()
        .join(",")
}

fn main() {
    let targets = [
        Grass { k: 2, n: 4 },
        Grass { k: 3, n: 6 },
        Grass { k: 4, n: 8 },
    ];

    let mut header = String::new();
    writeln!(
        header,
        "// AUTO-GENERATED by `cargo run --example generate_ts_lr_tables`."
    )
    .unwrap();
    writeln!(
        header,
        "// DO NOT EDIT. Regenerate from the Schubert Rust crate."
    )
    .unwrap();
    writeln!(header, "// SPDX-License-Identifier: Apache-2.0").unwrap();
    writeln!(header).unwrap();
    writeln!(
        header,
        "// Littlewood-Richardson coefficient tables for Schubert access"
    )
    .unwrap();
    writeln!(
        header,
        "// control, computed exactly by amari-enumerative. See the generator"
    )
    .unwrap();
    writeln!(
        header,
        "// (`examples/generate_ts_lr_tables.rs`) for the math."
    )
    .unwrap();
    writeln!(header).unwrap();
    writeln!(header, "export interface GrassmannianTable {{").unwrap();
    writeln!(header, "  /** k parameter of Gr(k,n). */").unwrap();
    writeln!(header, "  readonly k: number;").unwrap();
    writeln!(header, "  /** n parameter of Gr(k,n). */").unwrap();
    writeln!(header, "  readonly n: number;").unwrap();
    writeln!(header, "  /** Grassmannian dimension k*(n-k). */").unwrap();
    writeln!(header, "  readonly dim: number;").unwrap();
    writeln!(
        header,
        "  /** Point class partition (top Schubert class), codim = dim. */"
    )
    .unwrap();
    writeln!(header, "  readonly pointClass: readonly number[];").unwrap();
    writeln!(
        header,
        "  /** All partitions in the k*(n-k) box, as arrays. */"
    )
    .unwrap();
    writeln!(
        header,
        "  readonly partitions: readonly (readonly number[])[];"
    )
    .unwrap();
    writeln!(
        header,
        "  /** Pairwise product: key `\"λ|μ\"` -> list of `[νKey, coeff]`. */"
    )
    .unwrap();
    writeln!(
        header,
        "  readonly product: Readonly<Record<string, ReadonlyArray<readonly [string, number]>>>;"
    )
    .unwrap();
    writeln!(header, "}}").unwrap();
    writeln!(header).unwrap();
    writeln!(header, "export interface GrassmannianTables {{").unwrap();
    writeln!(header, "  readonly gr24: GrassmannianTable;").unwrap();
    writeln!(header, "  readonly gr36: GrassmannianTable;").unwrap();
    writeln!(header, "  readonly gr48: GrassmannianTable;").unwrap();
    writeln!(header, "}}").unwrap();
    writeln!(header).unwrap();
    writeln!(header, "export const TABLES: GrassmannianTables = {{").unwrap();

    for (idx, g) in targets.iter().enumerate() {
        emit_table(&mut header, g);
        if idx + 1 < targets.len() {
            writeln!(header).unwrap();
        }
    }

    writeln!(header, "}};").unwrap();
    print!("{header}");
}

fn emit_table(out: &mut String, g: &Grass) {
    let parts = g.partitions_in_box();
    let dim = g.dim();
    let point = Partition::new(vec![g.cols(); g.k]); // (n-k, ..., n-k) k times

    // Cross-check: the point class must be in our enumerated list and have
    // codimension == dim.
    assert_eq!(
        point.size(),
        dim,
        "point class codim != dim for Gr({},{})",
        g.k,
        g.n
    );
    assert!(
        parts.iter().any(|p| p == &point.parts),
        "point class {:?} not enumerated for Gr({},{})",
        point.parts,
        g.k,
        g.n
    );

    let n_parts = parts.len();

    // Build pairwise product table using the Grassmannian-restricted
    // Schubert product (NOT the full-ring LR product — out-of-box classes
    // are dropped, which is exactly the Grassmannian quotient).
    let unit = Partition::empty();
    let mut product_entries: Vec<(String, Vec<(String, u64)>)> = Vec::new();
    for la in &parts {
        let p_la = Partition::new(la.clone());
        for mu in &parts {
            let p_mu = Partition::new(mu.clone());
            let prod = schubert_product(&p_la, &p_mu, (g.k, g.n));
            if prod.is_empty() {
                continue; // e.g. σ₂·σ₁₁ = 0 on Gr(2,4)
            }
            let terms: Vec<(String, u64)> =
                prod.iter().map(|(nu, c)| (key(&nu.parts), *c)).collect();
            product_entries.push((format!("{}|{}", key(la), key(mu)), terms));
        }
    }

    // Sanity cross-check: the unit class σ_() is the multiplicative identity,
    // so σ_()·σ_ν must equal {ν: 1} for every in-box ν.
    for nu in &parts {
        let p_nu = Partition::new(nu.clone());
        let prod = schubert_product(&unit, &p_nu, (g.k, g.n));
        assert_eq!(
            prod.iter().collect::<Vec<_>>(),
            vec![(&p_nu, &1u64)],
            "unit-class identity failed for σ_()·σ_{{{}}} on Gr({},{})",
            key(nu),
            g.k,
            g.n
        );
    }

    let tag = format!("gr{}{}", g.k, g.n);
    writeln!(
        out,
        "  // Gr({},{}) — dim {}, {} partitions",
        g.k, g.n, dim, n_parts
    )
    .unwrap();
    writeln!(out, "  {}: {{", tag).unwrap();
    writeln!(out, "    k: {},", g.k).unwrap();
    writeln!(out, "    n: {},", g.n).unwrap();
    writeln!(out, "    dim: {},", dim).unwrap();
    writeln!(
        out,
        "    pointClass: [{}],",
        point
            .parts
            .iter()
            .map(|p| p.to_string())
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();
    writeln!(out, "    partitions: [").unwrap();
    for p in &parts {
        writeln!(
            out,
            "      [{}],",
            p.iter()
                .map(|x| x.to_string())
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
    }
    writeln!(out, "    ],").unwrap();
    writeln!(out, "    product: {{").unwrap();
    for (ek, terms) in &product_entries {
        let terms_str = terms
            .iter()
            .map(|(k, c)| format!("[\"{k}\", {c}]"))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(out, "      \"{ek}\": [{terms_str}],").unwrap();
    }
    writeln!(out, "    }},").unwrap();
    writeln!(out, "  }},").unwrap();

    eprintln!(
        "Gr({},{}) dim={} partitions={} product_entries={}",
        g.k,
        g.n,
        dim,
        n_parts,
        product_entries.len()
    );
}
